### ISSUE TITLE
If the module name contains `-`, it seems that the build variant is not recognized well.

### ISSUE THREAD

**Issue by ParkJong-Hun** [tomorrowkey/danger-compose_compiler_metrics#1]
```
[!] The exception involves the following plugins:
 -  danger-compose_compiler_metrics

/var/lib/gems/3.0.0/gems/json-2.7.2/lib/json/common.rb:250:in `read': \e[31m (Danger::DSLError)
[!] Invalid `Dangerfile-build` file: No such file or directory @ rb_sysopen - app-components-catalog/build/compose_compiler_metrics/app_components-module.json\e[0m
 #  from Dangerfile-build:4
 #  -------------------------------------------
 #    next if report_dir.include?("vendor/bundle")
 >    compose_compiler_metrics.report(report_dir)
 #  end
 #  -------------------------------------------
        from /var/lib/gems/3.0.0/gems/json-2.7.2/lib/json/common.rb:250:in `load_file'
        from /var/lib/gems/3.0.0/gems/danger-compose_compiler_metrics-0.0.4/lib/compose_compiler_metrics/plugin.rb:138:in `block in report'
        from /var/lib/gems/3.0.0/gems/danger-compose_compiler_metrics-0.0.4/lib/compose_compiler_metrics/plugin.rb:132:in `each'
        from /var/lib/gems/3.0.0/gems/danger-compose_compiler_metrics-0.0.4/lib/compose_compiler_metrics/plugin.rb:132:in `report'
        from Dangerfile-build:4:in `block in eval_file'
        from Dangerfile-build:2:in `each'
        from Dangerfile-build:2:in `eval_file'
        from /var/lib/gems/3.0.0/gems/danger-9.4.3/lib/danger/danger_core/dangerfile.rb:311:in `eval'
        from /var/lib/gems/3.0.0/gems/danger-9.4.3/lib/danger/danger_core/dangerfile.rb:311:in `eval_file'
        from /var/lib/gems/3.0.0/gems/danger-9.4.3/lib/danger/danger_core/dangerfile.rb:204:in `block in parse'
        from /var/lib/gems/3.0.0/gems/danger-9.4.3/lib/danger/danger_core/dangerfile.rb:201:in `instance_eval'
        from /var/lib/gems/3.0.0/gems/danger-9.4.3/lib/danger/danger_core/dangerfile.rb:201:in `parse'
        from /var/lib/gems/3.0.0/gems/danger-9.4.3/lib/danger/danger_core/dangerfile.rb:287:in `run'
        from /var/lib/gems/3.0.0/gems/danger-9.4.3/lib/danger/danger_core/executor.rb:28:in `run'
        from /var/lib/gems/3.0.0/gems/danger-9.4.3/lib/danger/commands/runner.rb:73:in `run'
        from /var/lib/gems/3.0.0/gems/claide-1.1.0/lib/claide/command.rb:334:in `run'
        from /var/lib/gems/3.0.0/gems/danger-9.4.3/bin/danger:5:in `<top (required)>'
        from /usr/local/bin/danger:25:in `load'
        from /usr/local/bin/danger:25:in `<main>'
/var/lib/gems/3.0.0/gems/json-2.7.2/lib/json/common.rb:250:in `read': No such file or directory @ rb_sysopen - app-components-catalog/build/compose_compiler_metrics/app_components-module.json (Errno::ENOENT)
        from /var/lib/gems/3.0.0/gems/json-2.7.2/lib/json/common.rb:250:in `load_file'
        from /var/lib/gems/3.0.0/gems/danger-compose_compiler_metrics-0.0.4/lib/compose_compiler_metrics/plugin.rb:138:in `block in report'
        from /var/lib/gems/3.0.0/gems/danger-compose_compiler_metrics-0.0.4/lib/compose_compiler_metrics/plugin.rb:132:in `each'
        from /var/lib/gems/3.0.0/gems/danger-compose_compiler_metrics-0.0.4/lib/compose_compiler_metrics/plugin.rb:132:in `report'
        from Dangerfile-build:4:in `block in eval_file'
        from Dangerfile-build:2:in `each'
        from Dangerfile-build:2:in `eval_file'
        from /var/lib/gems/3.0.0/gems/danger-9.4.3/lib/danger/danger_core/dangerfile.rb:311:in `eval'
        from /var/lib/gems/3.0.0/gems/danger-9.4.3/lib/danger/danger_core/dangerfile.rb:311:in `eval_file'
        from /var/lib/gems/3.0.0/gems/danger-9.4.3/lib/danger/danger_core/dangerfile.rb:204:in `block in parse'
        from /var/lib/gems/3.0.0/gems/danger-9.4.3/lib/danger/danger_core/dangerfile.rb:201:in `instance_eval'
        from /var/lib/gems/3.0.0/gems/danger-9.4.3/lib/danger/danger_core/dangerfile.rb:201:in `parse'
        from /var/lib/gems/3.0.0/gems/danger-9.4.3/lib/danger/danger_core/dangerfile.rb:287:in `run'
        from /var/lib/gems/3.0.0/gems/danger-9.4.3/lib/danger/danger_core/executor.rb:28:in `run'
        from /var/lib/gems/3.0.0/gems/danger-9.4.3/lib/danger/commands/runner.rb:73:in `run'
        from /var/lib/gems/3.0.0/gems/claide-1.1.0/lib/claide/command.rb:334:in `run'
        from /var/lib/gems/3.0.0/gems/danger-9.4.3/bin/danger:5:in `<top (required)>'
        from /usr/local/bin/danger:25:in `load'
        from /usr/local/bin/danger:25:in `<main>'

Exited with code exit status 1

```
As shown above, if the module name contains `-`(I'm not sure to work well if only one is included), it does not seem to look for files such as `module name_build variant-module.json`.

**Comment by ParkJong-Hun** [comment]
I'm not Ruby pro, but I think the reason is [this part](https://github.com/tomorrowkey/danger-compose_compiler_metrics/blob/main/lib/compose_compiler_metrics/helper.rb#L6) isn't a regular expression, so the module name and build variant name can't be extracted correctly.
